### ISSUE TITLE
Recreate the website in react + gatsby

### ISSUE THREAD

**Issue by denull0** [Embrace-clarity/clarity-website#7]
It's best if we move away from readymag so more people can work on the website

**Comment by neauoire** [comment]
I don’t know what readymag is, but if it’s just HTML and JS, put it on here. I can migrate it to something else.

👁‍🗨

**Comment by denull0** [comment]
@neauoire It's this https://readymag.com/ I am afraid the code exported is really dirty. They use some JS to place components on the canvas so there is no CSS or anything like that. 

P.S. Would also have to upgrade to $80 a month so I get access to the export feature 😭

**Comment by denull0** [comment]
@neauoire Decided to sacrifice 80 😄 Hope you can work with those files
